---
  - name: Copy docker-compose file
    template:
      src: templates/docker-compose.yml.j2
      dest: /root/docker/docker-compose.yml
    tags: update

  - name: Run Docker Compose
    command:
      cmd: docker compose up -d
      chdir: /root/docker
    tags: update
